### ISSUE TITLE
Week 4: comments

### ISSUE THREAD

**Issue by parvizi** [yokoso-capstone/yokoso#10]
Your progress slowed down this week. You should
1- Meet at least once per week.
2- Design the architecture in details according to requirements
3- Start programming

**Comment by meganhng** [comment]
Hi, we were actually meeting the day that you made this issue. We updated our meeting notes in the Wiki with the issues we discussed and we started working on low fidelity wireframes. 

We are planning on starting programming this weekend/ early next week
