### ISSUE TITLE
Create Components for Property Details Page

### ISSUE THREAD

**Issue by Txu045** [yokoso-capstone/yokoso#43]
Some sort of image carousel?
![image](https://user-images.githubusercontent.com/43283387/112176211-4a3d7e80-8bce-11eb-9c7f-89f10483797f.png)

Card Component
![image](https://user-images.githubusercontent.com/43283387/112176318-604b3f00-8bce-11eb-82d7-c7adcc31ac65.png)

**Comment by sttic** [comment]
Already doing/done this in #34 btw

**Comment by Txu045** [comment]
Dup Issue #34
