### ISSUE TITLE
Landing page positioning 

### ISSUE THREAD

**Issue by meganhng** [yokoso-capstone/yokoso#62]
Fix the padding on the landing page for smaller screens 
![image](https://user-images.githubusercontent.com/35239417/114287909-13be8b00-9a39-11eb-99db-d1b1f7eb6122.png)

**Comment by sttic** [comment]
Is the screenshot of the entire window? If it is and the window pretty short or zoomed in, then I'd argue this is the right behavior.

There comes a point where there's not enough room for the content (including sufficient padding like under the main text). When this happens we shouldn't avoid the scrollbar by doing things like cramming things together or reducing too much space.

**Comment by meganhng** [comment]
I couldn't upload a picture of the entire window because the image was too big, but the exact same thing is happening when I open the webpage on my laptop screen. I'll try to update the picture if I can compress it more

**Comment by meganhng** [comment]
fixed #63
